# Generated by Django 5.1.2 on 2024-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='equiped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.CharField(default='no image added', max_length=300),
        ),
    ]
