# Generated by Django 5.1.2 on 2024-11-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_annonces', '0002_annonce_equiped_annonce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='lease_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
